### ISSUE TITLE
Getupdate process killed

### ISSUE THREAD

**Issue by abmahmoodi** [mayoral/telegrammer#7] opened 2015-07-13 10:36 UTC
After a few hours when my bot has no traffic, its process killed.
this is my my code:

``` ruby
require 'daemons'
require 'telegrammer'
require_relative 'aparat'

class AparatMe
  attr_accessor :bot, :aparat
  def initialize
    p 'INIT'
    @bot = Telegrammer::Bot.new('XXX')
    @aparat = Aparat.new
  end

  def process_message_and_send
    @bot.get_updates do |message|
      puts "In chat #{message.chat.id}, @#{message.from.username} said: #{message.text}"
      rec_message = message.text
      if (!rec_message) || (rec_message.strip! == '')
        p 'ERROR'
      else
        begin      
          if rec_message[0..5] == '/start'
            @bot.send_message(chat_id: message.chat.id, text: "Please send a keyword with /video for example: /video dog")
          elsif rec_message[0..6] == '/video '
            result = @aparat.video_by_search(rec_message[7..-1])
            @bot.send_message(chat_id: message.chat.id, text: "First item of search: #{result}")
          else
            # @bot.send_message(chat_id: message.chat.id, text: "Please send your keyword with /video command.")
          end
        rescue Exception => e
          p e.message
        end
      end
    end
  end
end

Process.daemon(true)
aparat_me = AparatMe.new
aparat_me.process_message_and_send
```

**Comment by kennetham** [comment] 2015-07-21 04:42
Yeah I faced this too. Have no idea as well
@mayoral any idea?

**Comment by abmahmoodi** [comment] 2015-07-21 06:21
I implemented telegram api in my app and this problem solved. I will publish my application source code in github soon.

**Comment by kennetham** [comment] 2015-07-21 06:50
@abmahmoodi what was the issue and how did you fixed it?

**Comment by abmahmoodi** [comment] 2015-07-21 07:16
This is a version of telegram API implemented by myself:

``` ruby
class  TelegramBot
  attr_accessor :offset, :token

  END_POINT = 'https://api.telegram.org'

  def initialize(token)
    @offset = 0  
    @token = token
  end

  def api_response(response)
    if response.code < 500
      @body = response.response_body

      data = MultiJson.load(@body)
      @success = data["ok"]

      if @success
        @result = data["result"][0]
      else
        false
      end
    else
      # TODO: Raise an exception
    end
  end

  def get_updates(&block)
    loop do
      request = run_api('getUpdates', {offset: @offset, timeout: 60})
      begin
        res = api_response(request)
        if (res != nil) and (res != false)
          message = Message.new(res)
          @offset = message.update_id + 1
          yield message
        end
      rescue Exception => e
        p e.message
      end
    end
  end

  def send_message(chat_id:, text:)
    run_api('sendMessage', {chat_id: chat_id, text: text})
  end

  private
  def run_api(api_method, params)
    Typhoeus.post(
        "#{END_POINT}/bot#{@token}/#{api_method}",
        headers: {
                "User-Agent" => "AparatBot/0.1.0",
                "Accept" => "application/json"
              },
        body: params
      )
  end
end
```

**Comment by abmahmoodi** [comment] 2015-07-21 07:17
I think there is an unhandled exception in Telegrammer.

**Comment by mayoral** [comment] 2015-07-21 08:05
@abmahmoodi @kennetham  what exception are you getting?

@kennetham I suspect that this is something related with having long polling sessions without receiving data. Maybe for these situations Typhoeus is not the best option for this situation.

I've been very busy these days, but I have in mind to migrate to something like Faraday and test with some HTTP clients that explicitly support persistent connections, like Net::HTTP::Persistent, Patron or HTTPClient.

**Comment by kennetham** [comment] 2015-07-21 08:20
@mayoral I can't remember the error, but the long polling crashed as @abmahmoodi faced. No worries on that.
https://github.com/shouya/telegram-bot

I think it would be great if some of these components can be used in Telegrammer. It's very easy to call commands etc, and it looks cleaner. Otherwise it's going to be a long switch case of commands.

**Comment by mayoral** [comment] 2015-08-15 16:17
@abmahmoodi @kennetham I've just uploaded version 0.3.0 of the gem. Now it uses HTTPClient to do the requests, so it'll use persistent connections if the endpoint supports it.

Hopefully this will solve the crashes you are having with get_updates after a long time.

Please test it and close the issue if the problem is solved for you.

**Comment by mayoral** [comment] 2015-08-28 22:40
Closing for now. If the problem persist we'll reopen it again.

**Closed as completed by mayoral** 2015-08-28 22:40 UTC
